"""change product id to product name in stock entry

Revision ID: 04e828c7fce3
Revises: aab0d4b5796b
Create Date: 2025-10-13 11:37:27.658134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '04e828c7fce3'
down_revision: Union[str, Sequence[str], None] = 'aab0d4b5796b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_entries', sa.Column('product_name', sa.CHAR(length=36), nullable=False))
    op.drop_constraint(op.f('stock_entries_ibfk_1'), 'stock_entries', type_='foreignkey')
    op.create_foreign_key(None, 'stock_entries', 'products', ['product_name'], ['name'])
    op.drop_column('stock_entries', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_entries', sa.Column('product_id', mysql.CHAR(length=36), nullable=False))
    op.drop_constraint(None, 'stock_entries', type_='foreignkey')
    op.create_foreign_key(op.f('stock_entries_ibfk_1'), 'stock_entries', 'products', ['product_id'], ['id'])
    op.drop_column('stock_entries', 'product_name')
    # ### end Alembic commands ###
