"""remove batch number in stock entry

Revision ID: 420301af084b
Revises: 04e828c7fce3
Create Date: 2025-10-13 11:44:02.310435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '420301af084b'
down_revision: Union[str, Sequence[str], None] = '04e828c7fce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sale_items_ibfk_1'), 'sale_items', type_='foreignkey')
    op.drop_column('sale_items', 'batch_number')
    op.drop_index(op.f('batch_number'), table_name='stock_entries')
    op.drop_column('stock_entries', 'batch_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_entries', sa.Column('batch_number', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('batch_number'), 'stock_entries', ['batch_number'], unique=True)
    op.add_column('sale_items', sa.Column('batch_number', mysql.VARCHAR(length=100), nullable=False))
    op.create_foreign_key(op.f('sale_items_ibfk_1'), 'sale_items', 'stock_entries', ['batch_number'], ['batch_number'])
    # ### end Alembic commands ###
