"""Add stock_entries relationship to Product model

Revision ID: aab0d4b5796b
Revises: bbd59bf8c242
Create Date: 2025-10-11 18:12:13.606556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab0d4b5796b'
down_revision: Union[str, Sequence[str], None] = 'bbd59bf8c242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
