"""Update user, wallet, and product models

Revision ID: bbd59bf8c242
Revises: 1a1a612806cc
Create Date: 2025-10-09 15:03:15.335177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbd59bf8c242'
down_revision: Union[str, Sequence[str], None] = '1a1a612806cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('modified_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('sale_items', 'sale_price',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('stock_entries', 'cost_price',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('stock_entries', 'selling_price',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False))
    op.alter_column('stock_entries', 'selling_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('stock_entries', 'cost_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('sale_items', 'sale_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.drop_table('profiles')
    # ### end Alembic commands ###
