"""remove batch number in stock entry

Revision ID: c95b53579f2d
Revises: 420301af084b
Create Date: 2025-10-13 15:28:49.339562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c95b53579f2d'
down_revision: Union[str, Sequence[str], None] = '420301af084b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'total_amount',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('stock_entries', sa.Column('product_id', sa.CHAR(length=36), nullable=False))
    op.drop_constraint(op.f('stock_entries_ibfk_1'), 'stock_entries', type_='foreignkey')
    op.create_foreign_key(None, 'stock_entries', 'products', ['product_id'], ['id'])
    op.drop_column('stock_entries', 'product_name')
    op.alter_column('wallets', 'balance',
               existing_type=mysql.FLOAT(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.add_column('stock_entries', sa.Column('product_name', mysql.CHAR(length=36), nullable=False))
    op.drop_constraint(None, 'stock_entries', type_='foreignkey')
    op.create_foreign_key(op.f('stock_entries_ibfk_1'), 'stock_entries', 'products', ['product_name'], ['name'])
    op.drop_column('stock_entries', 'product_id')
    op.alter_column('sales', 'total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
