"""remove the wallat entity

Revision ID: ff155aa2fa43
Revises: c95b53579f2d
Create Date: 2025-10-16 10:26:37.413910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff155aa2fa43'
down_revision: Union[str, Sequence[str], None] = 'c95b53579f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.add_column('sales', sa.Column('payment_reference', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'sales', ['payment_reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='unique')
    op.drop_column('sales', 'payment_reference')
    op.create_table('wallets',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('balance', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('modified_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('wallets_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
